name: 🐛 Bug Report
description: Report a bug or unexpected behavior in causal inference functionality
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below to help us understand and reproduce the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Import causal_inference library
        2. Call attribution.fit() with data
        3. See error in computation
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 🏗️ Affected Component
      description: Which component is affected by this bug?
      options:
        - causal-api (FastAPI service)
        - causal-processor (background jobs)
        - causal_inference (core library)
        - attribution modeling
        - incrementality testing
        - media mix modeling
        - configuration management
        - database integration
        - observability/metrics
        - Docker/deployment
        - CI/CD Pipeline
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severity
      description: How severe is this bug?
      options:
        - Low - Minor issue, workaround available
        - Medium - Affects functionality but not critical
        - High - Blocks important functionality
        - Critical - System down or incorrect causal estimates
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Environment
      description: Environment details
      placeholder: |
        - OS: [e.g. macOS 14.0, Ubuntu 22.04]
        - Python Version: [e.g. 3.11.5]
        - Package Version: [e.g. 0.1.0]
        - Docker Version: [e.g. 24.0.6]
      value: |
        - OS: 
        - Python Version: 
        - Package Version: 
        - Docker Version: 
    validations:
      required: true

  - type: textarea
    id: data-context
    attributes:
      label: 📊 Data Context
      description: Information about the data that caused the issue (without sharing sensitive data)
      placeholder: |
        - Sample size: [e.g. 10,000 rows]
        - Data types: [e.g. numerical, categorical]
        - Missing values: [e.g. 5% missing]
        - Any data preprocessing applied

  - type: textarea
    id: logs
    attributes:
      label: 📋 Error Logs
      description: If applicable, add relevant error logs or stack traces
      placeholder: Paste error logs here...
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context about the problem here (screenshots, related issues, etc.)
      placeholder: Any additional information that might help...

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have provided all the requested information above
          required: true
        - label: I am willing to help test a fix for this bug
          required: false